# Generated by Django 5.2.17 on 2026-09-08 07:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('SLACK', 'Slack'), ('MICROSOFT_TEAMS', 'Microsoft Teams'), ('GOOGLE_CALENDAR', 'Google Calendar'), ('GOOGLE_DRIVE', 'Google Drive'), ('GITHUB', 'GitHub'), ('JIRA', 'Jira'), ('NOTION', 'Notion'), ('TRELLO', 'Trello'), ('LINEAR', 'Linear')], default='SLACK', max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('CONNECTED', 'Connected'), ('DISCONNECTED', 'Disconnected'), ('ERROR', 'Error')], default='DISCONNECTED', max_length=20)),
                ('credentials', models.JSONField(blank=True, default=dict)),
                ('integration_settings', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('connected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connected_integrations', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'status'], name='integration_organiz_aec7ec_idx'), models.Index(fields=['provider', 'status'], name='integration_provide_c23515_idx'), models.Index(fields=['connected_by', 'created_at'], name='integration_connect_df743a_idx')],
            },
        ),
    ]
