# Generated by Django 5.2.17 on 2026-09-09 11:02

from django.conf import settings
from django.db import migrations, models


def normalize_existing_owners(apps, schema_editor):
    Organization = apps.get_model("organizations", "Organization")
    OrganizationMember = apps.get_model("organizations", "OrganizationMember")
    for organization in Organization.objects.all().iterator():
        owners = list(
            OrganizationMember.objects.filter(
                organization_id=organization.pk,
                role="OWNER",
                is_active=True,
            ).order_by("created_at", "pk")
        )
        if not owners:
            continue
        keep = next((member for member in owners if member.user_id == organization.owner_id), owners[0])
        if organization.owner_id != keep.user_id:
            organization.owner_id = keep.user_id
            organization.save(update_fields=["owner_id"])
        OrganizationMember.objects.filter(
            organization_id=organization.pk,
            role="OWNER",
        ).exclude(pk=keep.pk).update(role="ADMIN")


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organizationinvitation_revoked_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(normalize_existing_owners, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='organizationmember',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'OWNER')), fields=('organization',), name='unique_owner_per_organization'),
        ),
    ]
