# Generated by Django 5.2.17 on 2026-09-10 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organizationmember_unique_owner_per_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationinvitation',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('PROJECT_MANAGER', 'Team Lead'), ('MEMBER', 'Developer'), ('QA', 'QA'), ('VIEWER', 'Viewer')], default='MEMBER', max_length=30),
        ),
        migrations.AlterField(
            model_name='organizationmember',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('PROJECT_MANAGER', 'Team Lead'), ('MEMBER', 'Developer'), ('QA', 'QA'), ('VIEWER', 'Viewer')], default='MEMBER', max_length=30),
        ),
    ]
